### ISSUE TITLE
Gallery Submission Feedback - Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by yeeha567** [jaimeneto85/utm_whatsapp#1]
When reviewing your template, we've noticed that `gtmOnSuccess` or `gtmOnFailure` are called incorrectly. This is required so that users can sequence their tags correctly.

**Comment by jaimeneto85** [comment]
@yeeha567 done! I updated my code. Could you check again? or I need to re-submit to Gallery?
