### ISSUE TITLE
Gallery Submission Feedback - Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by yeeha567** [jaimeneto85/utm_whatsapp#2]
https://github.com/jaimeneto85/utm_whatsapp/blob/13b239aa3487670a4f03976e6d613163e718c967/template.tpl#L61

When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by jaimeneto85** [comment]
@yeeha567 done! I added the econdeUriComponent in the urL:
```javascript
injectScript('https://singularidata.com/static/utm_whatsapp.js?clientId='+encodeUriComponent(clientId)+"&v="+encodeUriComponent(getTimestampMillis()), data.gtmOnSuccess(), data.gtmOnFailure());
```

**Comment by jaimeneto85** [comment]
@yeeha567 could you review my last fix?
